name: OpenTofu Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**/*'
      - '!v*' # Don't run on release branches.
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.tftest.hcl'
      - '.github/workflows/test.yml'
      - '!version.json' # Needed as this file is modifed by release workflow!

# Ensures that only one deploy task run at a time.
concurrency:
  group: tofu

permissions:
  # required for all workflows
  contents: write
  checks: write
  pull-requests: write
  discussions: write
  statuses: write
  id-token: write # This is required for requesting the JWT for oidc AUthentication

# Run Tests
jobs:
  base:
    name: Base Test
    uses: otc-code/code-workflows/.github/workflows/tofu_test_aws.yml@main
    secrets: inherit
    with:
      EXAMPLES: "['10-simple','20-advanced','30-complex']"
      CLOUD_REGIONS: "['eu-central-1']"
